Merge unittest and coverage reports

diff --git a/.github/workflows/generate_reports.yml b/.github/workflows/generate_reports.yml
--- a/.github/workflows/generate_reports.yml
+++ b/.github/workflows/generate_reports.yml
@@ -1,7 +1,7 @@
-# This workflow will install Python dependencies, run unit tests and create a coverage report
+# This workflow will install Python dependencies, run unit tests and create coverage and unit test reports
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
 
-name: Create coverage
+name: Generate reports
 
 on:
   push:
@@ -10,7 +10,7 @@ on:
     branches: [ "main", "develop" ]
 
 jobs:
-  generate:
+  generate-coverage:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -45,9 +45,40 @@ jobs:
         name: coverage-report-${{ matrix.python-version }}
         path: test/reports/coverage-${{ matrix.python-version }}.xml
 
+  generate-unittest:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
+    steps:
+    - uses: actions/checkout@v4
+    - uses: actions/cache@v4
+      id: cache-venv
+      with:
+        path: ./.venv/
+        key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
+        restore-keys: ${{ runner.os }}-venv-${{ matrix.python-version }}-
+    - name: Set up Python ${{ matrix.python-version }}
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install venv on cache miss
+      run: python src/scripts/venv_setup.py --recreate
+      if: steps.cache-venv.outputs.cache-hit != 'true'
+    - name: Generate unit test XML
+      run: |
+        . ./.venv/bin/activate
+        python -m xmlrunner discover -o test/reports/unit-${{ matrix.python-version }}.xml
+    - name: Upload unit test report
+      uses: actions/upload-artifact@v4
+      with:
+        name: unit-report-${{ matrix.python-version }}
+        path: test/reports/unit-${{ matrix.python-version }}.xml
+
   commit:
     runs-on: ubuntu-latest
-    needs: generate
+    needs: [generate-coverage, generate-unittest]
     steps:
     - uses: actions/checkout@v4
     - name: Extract branch name
@@ -59,18 +90,26 @@ jobs:
       with:
         pattern: coverage-report-*
         path: downloaded-reports
+    - name: Download unit reports
+      uses: actions/download-artifact@v4
+      with:
+        pattern: unit-report-*
+        path: downloaded-reports
     - name: Copy reports to test/reports
-      run: cp downloaded-reports/coverage-report-*/coverage-*.xml test/reports/
+      run: cp downloaded-reports/*/*.xml test/reports/
     - name: Commit reports to the repo
       uses: EndBug/add-and-commit@v9
       with:
         new_branch: ${{ steps.extract_branch.outputs.branch }}
         default_author: github_actions
-        add: test/reports/coverage-*.xml --force
-        message: 'Append coverage reports'
+        add: test/reports/*.xml --force
+        message: 'Append reports'
 
   comment:
-    # Share the reports as comments.
+    # Share the reports as comments.    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
     runs-on: ubuntu-latest
     needs: commit
     strategy:
@@ -81,10 +120,19 @@ jobs:
     - uses: actions/checkout@v4
     - name: Check coverage file exists
       run: if [ ! -f test/reports/coverage-${{ matrix.python-version }}.xml ]; then echo "Coverage file not found"; exit 1; fi
-    - name: 'Append report'
+    - name: Check unit test file exists
+      run: if [ ! -f test/reports/unit-${{ matrix.python-version }}.xml ]; then echo "Unit test file not found"; exit 1; fi
+    - name: 'Append coverage report'
       uses: kamilok04/coverage-with-title@main
       with:
         coverageFile: test/reports/coverage-${{ matrix.python-version }}.xml
         token: ${{ secrets.GITHUB_TOKEN }}
         title: 'Python (${{ matrix.python-version }}) Coverage Report'
         thresholdAll: 0.8
+    - name: 'Append unit test report'
+      uses: dorny/test-reporter@v2
+      with:
+        name: 'Python (${{ matrix.python-version }}) Unit Test Report'
+        path: test/reports/unit-${{ matrix.python-version }}.xml
+        reporter: java-junit
+        comment-on: commit
