Revert the new workspace change

diff --git a/.github/workflows/generate_coverage.yml b/.github/workflows/generate_coverage.yml
--- a/.github/workflows/generate_coverage.yml
+++ b/.github/workflows/generate_coverage.yml
@@ -54,16 +54,37 @@ jobs:
       shell: bash
       run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
       id: extract_branch
+    - name: Download coverage reports
+      uses: actions/download-artifact@v4
+      with:
+        pattern: coverage-report-*
+        path: downloaded-reports
+    - name: Copy reports to test/reports
+      run: cp downloaded-reports/coverage-report-*/coverage-*.xml test/reports/
+    - name: Commit reports to the repo
+      uses: EndBug/add-and-commit@v9
+      with:
+        new_branch: ${{ steps.extract_branch.outputs.branch }}
+        default_author: github_actions
+        add: test/reports/coverage-*.xml --force
+        message: 'Append coverage reports'
 
   comment:
     # Share the reports as comments.
     runs-on: ubuntu-latest
     needs: commit
+    strategy:
+      fail-fast: false
+      matrix:
+        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
     steps:
+    - uses: actions/checkout@v4
+    - name: Check coverage file exists
+      run: if [ ! -f test/reports/coverage-${{ matrix.python-version }}.xml ]; then echo "Coverage file not found"; exit 1; fi
     - name: 'Append report'
-      uses: dorny/test-reporter@v2
+      uses: kamilok04/coverage-with-title@main
       with:
-        artifact: /coverage-report-(.*)/
-        name: 'Python $1 Coverage Report'
-        path: coverage-*.xml
-        reporter: python-xunit
+        coverageFile: test/reports/coverage-${{ matrix.python-version }}.xml
+        token: ${{ secrets.GITHUB_TOKEN }}
+        title: 'Python (${{ matrix.python-version }}) Coverage Report'
+        thresholdAll: 0.8
